name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo hello word;

      - name: run a mutil-line script
        run:
          echo add onther to build
          echo test, and deploy you project